# site information {{{
title: Your awesome title
description: >
  Awesome description here
# }}}

# URL {{{
url: "https://spudowiar.github.io"
baseurl: ""
# }}}

# contact information {{{
email: spudowiar@outlook.com
twitter_username: spudowiar
github_username:  spudowiar
# }}}

# markdown {{{
markdown: redcarpet
# }}}

# vim: fdm=marker
