# site information {{{
title: cat /dev/urandom
description: "# Saleem Rashid"
# }}}

# URL {{{
url: "https://spudowiar.github.io"
baseurl: ""
# }}}

# contact information {{{
email: spudowiar@outlook.com
twitter_username: spudowiar
github_username:  spudowiar
# }}}

# markdown {{{
markdown: redcarpet
# }}}

# theme {{
theme:
    # main {{{
    fonts: '"Source Sans Pro", sans-serif'
    monospace-fonts: '"Source Code Pro", monospace'
    content-padding: 2em 2em 2em 2em
    content-padding-left: 6em
    content-padding-right: 2em
    # }}}

    # theme {{{
    theme-color: "#181818"
    theme-text-color: "#d8d8d8"
    theme-color-accent: "#585858"
    # }}}

    # title {{{
    site-title-monospace: true
    site-title-prompt: true
    # }}}

    # navigation {{{
    navigation-width: 16em
    navigation-padding-left: 1em
    navigation-padding-right: 2em
    navigation-padding-anchor: 2em
    navigation-max-width: 25%
    navigation-side: left
    navigation-anchor: bottom
    # }}}
# }}}

# vim: fdm=marker
