# site information {{{
title: cat life > /dev/urandom
title_prefix: "spudowiar: "
description: "# Saleem Rashid"
keep_files:
    - .nojekyll
# }}}

# URL {{{
url: "https://spudowiar.github.io"
baseurl: ""
# }}}

# contact information {{{
email: spudowiar@outlook.com
twitter_username: spudowiar
github_username:  spudowiar
# }}}

# plugins {{{
markdown: redcarpet
redcarpet:
    extensions:
        - no_intra_emphasis

highlighter: pygments

gems:
    - jemoji
# }}}

# theme {{{
theme:
    # main {{{
    fonts: '"Source Sans Pro", sans-serif'
    font-size: 16px
    monospace-fonts: '"Source Code Pro", monospace'
    content-padding: 2em 1em 2em 1em
    content-padding-vertical: 2em 1em 2em 3em
    content-max-width: 64em
    # }}}

    # theme {{{
    theme-color: "#181818"
    theme-text-color: "#d8d8d8"
    theme-color-accent: "#585858"
    # }}}

    # title {{{
    site-title-monospace: true
    site-title-prompt: true
    # }}}

    # navigation {{{
    navigation-width: 20em
    navigation-padding-left: 1em
    navigation-padding-right: 2em
    navigation-padding-anchor: 2em
    navigation-max-width: 32%
    navigation-side: left
    navigation-anchor: bottom
    # }}}
# }}}

# vim: fdm=marker
