# site information {{{
title: cat life > /dev/urandom
description: Blog about computing, programming and stuff
tagline: "# Saleem Rashid"
keep_files:
    - .nojekyll
# }}}

# configuration {{{
title_prefix: "spudowiar: "
permalink: pretty

defaults:
    - scope:
        type: "posts"
      values:
        layout: "post"
    - scope:
        type: "drafts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"
# }}}

# URL {{{
url: "https://spudowiar.github.io"
baseurl: ""
# }}}

# contact information {{{
email: spudowiar@outlook.com
twitter_username: spudowiar

github_username:  spudowiar
github_repo: spudowiar.github.io
github_branch: jekyll
# }}}

# plugins {{{
markdown: redcarpet
redcarpet:
    extensions:
        - no_intra_emphasis
        - smart
        - strikethrough
    pygments:
        linenos: table

highlighter: pygments

gems:
    - jemoji
# }}}

# theme {{{
theme:
    # main {{{
    fonts: '"Source Sans Pro", sans-serif'
    font-size: 17px
    monospace-fonts: '"Source Code Pro", monospace'
    content-padding: 2em 1em 2em 1em
    content-padding-vertical: 2em 1em 2em 3em
    content-max-width: 53em
    # }}}

    # theme {{{
    theme-color: "#181818"
    theme-text-color: "#d8d8d8"
    theme-color-accent: "#a1b56c"
    # }}}

    # title {{{
    site-title-monospace: true
    site-title-prompt: true
    # }}}

    # navigation {{{
    navigation-width: 19em
    navigation-padding-left: 1em
    navigation-padding-right: 1.75em
    navigation-padding-anchor: 2em
    navigation-max-width: 32%
    navigation-side: left
    navigation-anchor: bottom
    # }}}
# }}}

# vim: fdm=marker
